In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [2]:
((np.ones(20)*2)**np.arange(1,21))/(np.arange(1,21))

array([2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
       6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
       5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
       6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
       7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [3]:
np.sum((np.ones(6)*0.1)**(np.arange(6)*3)*(np.ones(6)*0.2)**(np.arange(6)*4))

1.00000160000256

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [4]:
zeros = np.zeros((8,8))
np.where(np.indices(zeros.shape).sum(axis=0) % 2, zeros, 1)

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [5]:
X = np.random.random((5, 2))
display(X)
X[:,0] = np.sqrt(X[:,0]**2 + X[:,1]**2)
X[:,1] = np.arctan(X[:,1] / X[:,0])
X

array([[0.88800702, 0.30378297],
       [0.14515938, 0.05542482],
       [0.17046442, 0.74204421],
       [0.55462573, 0.82897432],
       [0.16147898, 0.1975894 ]])

array([[0.93853107, 0.3130368 ],
       [0.15538068, 0.34263414],
       [0.76137227, 0.77254278],
       [0.99740068, 0.69343932],
       [0.25518039, 0.65888048]])

**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [6]:
X = np.random.random((10, 10))
display(X)
np.unravel_index(np.argmax(X), X.shape)

array([[0.51963001, 0.99509644, 0.14853356, 0.44404873, 0.73883289,
        0.56304802, 0.31430654, 0.84916073, 0.22341914, 0.28291678],
       [0.56269476, 0.9742843 , 0.07068905, 0.02496543, 0.42989293,
        0.0835779 , 0.86238209, 0.09028024, 0.0446295 , 0.53975767],
       [0.26906025, 0.59563462, 0.36840936, 0.55646746, 0.64441875,
        0.47045052, 0.04922308, 0.68326579, 0.30558891, 0.70058779],
       [0.28301168, 0.98465557, 0.16319192, 0.08051431, 0.95405056,
        0.69622575, 0.74842614, 0.61639443, 0.86751278, 0.0896976 ],
       [0.90704507, 0.48673635, 0.01080567, 0.37013547, 0.91155251,
        0.73040617, 0.34784504, 0.70585402, 0.99463769, 0.31362533],
       [0.65179178, 0.18895092, 0.55046511, 0.37168049, 0.24410224,
        0.23646036, 0.01122539, 0.06937446, 0.14552753, 0.53750587],
       [0.65020881, 0.87581331, 0.70543823, 0.10147711, 0.95282992,
        0.18415979, 0.76228718, 0.22815007, 0.05579039, 0.88473488],
       [0.92504366, 0.25649309, 0.2078707

(0, 1)

**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [7]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))

display(X,y)
X[np.linalg.norm(X-y, axis=1).argmin()]

array([[0.66123798, 0.71618591],
       [0.03793425, 0.33662811],
       [0.38694714, 0.94516928],
       [0.05046154, 0.01536373],
       [0.28856164, 0.01263378],
       [0.7376302 , 0.66544188],
       [0.9283833 , 0.13689806],
       [0.8168943 , 0.89168706],
       [0.20314438, 0.20176234],
       [0.92783938, 0.74115716]])

array([[0.52546198, 0.90929601]])

array([0.38694714, 0.94516928])

**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [8]:
x = np.linspace(-3, 3, 7)
display(x)
np.piecewise(x, [x < 0, (0 <= x) * (x <= 2), x >= 2], [
            lambda x: x**2 + 2*x + 6, 
            lambda x: x+6, 
            lambda x: x**2 + 4*x - 4
])

array([-3., -2., -1.,  0.,  1.,  2.,  3.])

array([ 9.,  6.,  5.,  6.,  7.,  8., 17.])

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [9]:
X = np.random.random((10, 10))

x_means = np.mean(X, axis=0)
X_adjusted = X - x_means

np.mean(X_adjusted, axis=0)

array([-6.66133815e-17,  4.44089210e-17, -3.33066907e-17, -4.44089210e-17,
        4.44089210e-17, -5.55111512e-17,  1.60982339e-16,  3.33066907e-17,
       -8.88178420e-17, -4.44089210e-17])

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [10]:
X = np.random.normal(loc=5, scale=2., size=1000)
np.mean(X), np.var(X)

(4.944748292555172, 4.202748471105962)

**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [11]:
np.indices((5,5)).sum(axis=0)%5

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 0],
       [2, 3, 4, 0, 1],
       [3, 4, 0, 1, 2],
       [4, 0, 1, 2, 3]], dtype=int32)

**11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [12]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)    

[0, 4, 4, 0, 4]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [13]:
def sample(x, c):
    r = np.random.random(c) * np.sum(x)
    y = (x @ np.triu(np.ones(c))).reshape((c, 1)) 
    res = r - y
    return list(np.where(res < 0, res, -np.inf).argmax(axis=0))

In [14]:
sample([50, 3, 1, 7, 20], 5)

[0, 0, 0, 0, 3]